name: Exportar Excel y subir a Release

on:
  schedule:
    - cron: '*/30 * * * *'  # Ejecuta cada 30 minutos
  workflow_dispatch:

jobs:
  exportar_y_subir:
    runs-on: ubuntu-latest

    steps:
    - name: Clonar repo
      uses: actions/checkout@v3

    - name: Configurar Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Instalar dependencias
      run: |
        python -m pip install --upgrade pip
        pip install pandas numpy requests openpyxl google-auth google-api-python-client

    - name: Ejecutar script
      run: python script.py  # Asegúrate de que así se llame tu archivo

    - name: Crear Release (si no existe)
      id: create_release
      uses: softprops/action-gh-release@v1
      with:
        tag_name: auto
        name: Actualización automática
        body: Base limpia generada automáticamente
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Subir archivo Excel a la Release
      uses: softprops/action-gh-release@v1
      with:
        tag_name: auto
        files: Respuestas_610.xlsx
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
